"""Shared permission constants (per-feature modules)."""

from shared_auth_lib.permissions.admin import (
    ADMIN_READ,
)
from shared_auth_lib.permissions.finance import (
    FINANCE_ADMIN,
    FINANCE_EXPENSES_APPROVE,
    FINANCE_EXPENSES_READ,
    FINANCE_EXPENSES_WRITE,
    FINANCE_EXPORT,
    FINANCE_INVOICES_READ,
    FINANCE_INVOICES_SEND,
    FINANCE_INVOICES_WRITE,
    FINANCE_VIEW,
    FINANCE_WRITE,
)
from shared_auth_lib.permissions.hr import (
    HR_ATTENDANCE_APPROVE,
    HR_ATTENDANCE_EXCEPTIONS_MANAGE,
    HR_ATTENDANCE_EXPORT,
    HR_ATTENDANCE_MANUAL_CREATE,
    HR_ATTENDANCE_READ,
    HR_ATTENDANCE_SYNC,
    HR_EMPLOYEES_READ,
    HR_EMPLOYEES_SYNC,
    HR_HIKCENTRAL_READ,
    HR_RECRUITMENT_APPLICATION_READ,
    HR_RECRUITMENT_APPLICATION_UPDATE,
    HR_RECRUITMENT_POSTING_CREATE,
    HR_RECRUITMENT_POSTING_PUBLISH,
    HR_RECRUITMENT_POSTING_UPDATE,
)
from shared_auth_lib.permissions.lead import (
    LEAD_ASSIGN,
    LEAD_CLAIM,
    LEAD_CREATE,
    LEAD_DELETE,
    LEAD_UPDATE,
    LEAD_VIEW,
)
from shared_auth_lib.permissions.listing import (
    LISTING_CREATE,
    LISTING_DELETE,
    LISTING_UPDATE,
    LISTING_VIEW,
)
from shared_auth_lib.permissions.media import (
    MEDIA_DELETE,
    MEDIA_UPDATE,
    MEDIA_UPLOAD,
    MEDIA_VIEW,
)
from shared_auth_lib.permissions.lms import (
    LMS_AGENT_VIEW_STATS,
    LMS_ASSIGNMENT_CREATE,
    LMS_QUIZ_PUBLISH,
    LMS_QUIZ_VIEW_PROGRESS,
)
from shared_auth_lib.permissions.task import (
    TASK_ASSIGN,
    TASK_CREATE,
    TASK_DELETE,
    TASK_EDIT,
    TASK_VIEW,
)

__all__ = [
    # admin
    "ADMIN_READ",
    # finance
    "FINANCE_ADMIN",
    "FINANCE_EXPENSES_APPROVE",
    "FINANCE_EXPENSES_READ",
    "FINANCE_EXPENSES_WRITE",
    "FINANCE_EXPORT",
    "FINANCE_INVOICES_READ",
    "FINANCE_INVOICES_SEND",
    "FINANCE_INVOICES_WRITE",
    "FINANCE_VIEW",
    "FINANCE_WRITE",
    # hr
    "HR_ATTENDANCE_APPROVE",
    "HR_ATTENDANCE_EXCEPTIONS_MANAGE",
    "HR_ATTENDANCE_EXPORT",
    "HR_ATTENDANCE_MANUAL_CREATE",
    "HR_ATTENDANCE_READ",
    "HR_ATTENDANCE_SYNC",
    "HR_EMPLOYEES_READ",
    "HR_EMPLOYEES_SYNC",
    "HR_HIKCENTRAL_READ",
    "HR_RECRUITMENT_APPLICATION_READ",
    "HR_RECRUITMENT_APPLICATION_UPDATE",
    "HR_RECRUITMENT_POSTING_CREATE",
    "HR_RECRUITMENT_POSTING_PUBLISH",
    "HR_RECRUITMENT_POSTING_UPDATE",
    # lead
    "LEAD_ASSIGN",
    "LEAD_CLAIM",
    "LEAD_CREATE",
    "LEAD_DELETE",
    "LEAD_UPDATE",
    "LEAD_VIEW",
    # listing
    "LISTING_CREATE",
    "LISTING_DELETE",
    "LISTING_UPDATE",
    "LISTING_VIEW",
    # media
    "MEDIA_DELETE",
    "MEDIA_UPDATE",
    "MEDIA_UPLOAD",
    "MEDIA_VIEW",
    # lms
    "LMS_AGENT_VIEW_STATS",
    "LMS_ASSIGNMENT_CREATE",
    "LMS_QUIZ_PUBLISH",
    "LMS_QUIZ_VIEW_PROGRESS",
    # task
    "TASK_ASSIGN",
    "TASK_CREATE",
    "TASK_DELETE",
    "TASK_EDIT",
    "TASK_VIEW",
]
